use_frameworks!

target 'RMCircularAlert_Example' do
  pod 'RMCircularAlert', :path => '../'

  target 'RMCircularAlert_Tests' do
    inherit! :search_paths

    pod 'RMCircularAlert', :path => '../'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
